package com.sc.ap.core;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.sc.ap.model.LogOp;
import com.sc.ap.model.Param;
import com.sc.ap.model.Res;
import com.sc.ap.model.Role;
import com.sc.ap.model.RoleRes;

import com.sc.ap.model.User;
import com.sc.ap.model.UserRole;


/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {

		arp.addMapping("log_op", "id", LogOp.class);

		arp.addMapping("s_param", "id", Param.class);
		arp.addMapping("s_res", "id", Res.class);
		arp.addMapping("s_role", "id", Role.class);
		arp.addMapping("s_role_res", "id", RoleRes.class);

		arp.addMapping("s_user", "id", User.class);
		arp.addMapping("s_user_role", "id", UserRole.class);

	}
}
