package com.sc.ap.model;


import com.sc.ap.model.base.BaseDd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dd extends BaseDd<Dd> {
	public static final Dd dao = new Dd().dao();
}
