package com.sc.ap.model;

import com.sc.ap.model.base.BaseGenCfgCol;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenCfgCol extends BaseGenCfgCol<GenCfgCol> {
	public static final GenCfgCol dao = new GenCfgCol().dao();
}
