package com.sc.ap.model;

import com.sc.ap.model.base.BaseGenCfg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenCfg extends BaseGenCfg<GenCfg> {
	public static final GenCfg dao = new GenCfg().dao();
}
