package com.sc.ap.model;

import cn.hutool.core.util.StrUtil;
import com.alibaba.fastjson.JSON;
import com.sc.ap.model.base.BaseGenCfgCol;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenCfgCol extends BaseGenCfgCol<GenCfgCol> {

	private String attributeName;

	public static final GenCfgCol dao = new GenCfgCol().dao();

	public String getAttributeName() {
		return attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public Map<String,Object> getConfigJSON(){
		return StrUtil.isNotBlank(getTxt())? JSON.parseObject(getTxt(), HashMap.class):null;
	}

}
