package com.sc.ap.model;

import com.sc.ap.model.base.BaseGenCfgTbl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenCfgTbl extends BaseGenCfgTbl<GenCfgTbl> {
	public static final GenCfgTbl dao = new GenCfgTbl().dao();
}
