package com.sc.ap.model;


import com.sc.ap.model.base.BaseLogOp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogOp extends BaseLogOp<LogOp> {
	public static final LogOp dao = new LogOp().dao();
}
