package com.sc.ap.model;

import com.sc.ap.model.base.BaseResSer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResSer extends BaseResSer<ResSer> {
	public static final ResSer dao = new ResSer().dao();
}
