package com.sc.ap.model;

import com.sc.ap.model.base.BaseSer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ser extends BaseSer<Ser> {
	public static final Ser dao = new Ser().dao();
}
