package com.sc.ap.model;
import cn.hutool.core.util.StrUtil;
import com.sc.ap.kits.DateKit;
import com.sc.ap.model.base.BaseSer;

/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class Ser extends BaseSer<Ser> {
	public static final Ser dao = new Ser().dao();
            public String getTypeStr(){
                    return "0".equals(getType())?"服务":"";
            }

}
