package com.sc.ap.model;


import com.sc.ap.model.base.BaseUser;
import java.util.ArrayList;
import java.util.List;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

	public static final User dao = new User().dao();

	public String getStatusTxt(){
		return super.getStatusTxt(getStatus());
	}

	public User findByNickname(String nickname){
		String sql="select * from s_user where nickname=?";
		return dao.findFirst(sql,nickname);
	}

	public List<String> getRolesName(){
		List<String> list=new ArrayList<>();
		for (Role role:Role.dao.findRolesByUserId(getId())){
			list.add(role.getName());
		}
		return list;
	}
	public List<String> getRoleIds(){
		List<String> list=new ArrayList<>();
		for (Role role:Role.dao.findRolesByUserId(getId())){
			list.add(role.getId().toString());
		}
		return list;
	}
}
