package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGenCfgCol<M extends BaseGenCfgCol<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setTblId(Integer tblId) {
		set("tblId", tblId);
	}
	
	public Integer getTblId() {
		return getInt("tblId");
	}

	public void setCol(String col) {
		set("col", col);
	}
	
	public String getCol() {
		return getStr("col");
	}

	public void setTpe(String tpe) {
		set("tpe", tpe);
	}

	public String getTpe() {
		return getStr("tpe");
	}

	public void setTxt(String txt) {
		set("txt", txt);
	}
	
	public String getTxt() {
		return getStr("txt");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setOpId(Integer opId) {
		set("opId", opId);
	}
	
	public Integer getOpId() {
		return getInt("opId");
	}

	public void setNote(String note) {
		set("note", note);
	}

	public String getNote() {
		return getStr("note");
	}

	public void setOrgCol(String orgCol) {
		set("orgCol", orgCol);
	}

	public String getOrgCol() {
		return getStr("orgCol");
	}

}
