package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleRes<M extends BaseRoleRes<M>> extends CoreModel<M> implements IBean {

	public void setRoleId(Integer roleId) {
		set("roleId", roleId);
	}
	
	public Integer getRoleId() {
		return getInt("roleId");
	}

	public void setResId(Integer resId) {
		set("resId", resId);
	}
	
	public Integer getResId() {
		return getInt("resId");
	}

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

}
