package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRole<M extends BaseUserRole<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}
	public void setLoginname(String loginname) {
		set("loginname", loginname);
	}
	
	public String getLoginname() {
		return getStr("loginname");
	}

	public void setRoleCode(String roleCode) {
		set("roleCode", roleCode);
	}
	
	public String getRoleCode() {
		return getStr("roleCode");
	}

}
