package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseParam<M extends BaseParam<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}


	public void setK(String k) {
		set("k", k);
	}
	
	public String getK() {
		return getStr("k");
	}

	public void setVal(String val) {
		set("val", val);
	}
	
	public String getVal() {
		return getStr("val");
	}

	public void setNote(String note) {
		set("note", note);
	}
	
	public String getNote() {
		return getStr("note");
	}

	public void setOpId(Integer opId) {
		set("opId", opId);
	}
	
	public Integer getOpId() {
		return getInt("opId");
	}

	public void setLAt(java.util.Date lAt) {
		set("lAt", lAt);
	}
	
	public java.util.Date getLAt() {
		return get("lAt");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

}
