package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGenCfg<M extends BaseGenCfg<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setGsId(Integer gsId) {
		set("gsId", gsId);
	}
	
	public Integer getGsId() {
		return getInt("gsId");
	}

	public void setTbl(String tbl) {
		set("tbl", tbl);
	}
	
	public String getTbl() {
		return getStr("tbl");
	}

	public void setCol(String col) {
		set("col", col);
	}
	
	public String getCol() {
		return getStr("col");
	}

	public void setTxt(String txt) {
		set("txt", txt);
	}
	
	public String getTxt() {
		return getStr("txt");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setOpId(Integer opId) {
		set("opId", opId);
	}
	
	public Integer getOpId() {
		return getInt("opId");
	}

}
