package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}


	public void setLoginname(String loginname) {
		set("loginname", loginname);
	}
	
	public String getLoginname() {
		return getStr("loginname");
	}

	public void setPassword(String password) {
		set("password", password);
	}
	
	public String getPassword() {
		return getStr("password");
	}

	public void setNickname(String nickname) {
		set("nickname", nickname);
	}
	
	public String getNickname() {
		return getStr("nickname");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public void setEmail(String email) {
		set("email", email);
	}
	
	public String getEmail() {
		return getStr("email");
	}

	public void setAvatar(String avatar) {
		set("avatar", avatar);
	}
	
	public String getAvatar() {
		return getStr("avatar");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setSalt(String salt) {
		set("salt", salt);
	}
	
	public String getSalt() {
		return getStr("salt");
	}

	public void setLAt(java.util.Date lat) {
		set("lAt", lat);
	}
	
	public java.util.Date getLAt() {
		return get("lAt");
	}

	public void setOpId(Integer opId) {
		set("opId", opId);
	}
	
	public Integer getOpId() {
		return getInt("opId");
	}

	public void setCAt(java.util.Date cat) {
		set("cAt", cat);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dat) {
		set("dAt", dat);
	}
	
	public java.util.Date getDAt() {
		return get("dAt");
	}

}
