package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDd<M extends BaseDd<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}


	public void setCode(String code) {
		set("code", code);
	}
	
	public String getCode() {
		return getStr("code");
	}

	public void setTxt(String txt) {
		set("txt", txt);
	}
	
	public String getTxt() {
		return getStr("txt");
	}

	public void setOpId(Integer opId) {
		set("opId", opId);
	}
	
	public Integer getOpId() {
		return getInt("opId");
	}

	public void setModule(String module) {
		set("module", module);
	}
	
	public String getModule() {
		return getStr("module");
	}

	public void setIdx(Integer idx) {
		set("idx", idx);
	}
	
	public Integer getIdx() {
		return getInt("idx");
	}

	public void setParentId(Long parentId) {
		set("parentId", parentId);
	}
	
	public Long getParentId() {
		return getLong("parentId");
	}

	public void setLAt(java.util.Date lAt) {
		set("lAt", lAt);
	}
	
	public java.util.Date getLAt() {
		return get("lAt");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}
	
	public java.util.Date getDAt() {
		return get("dAt");
	}

}
