package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGenCfgTbl<M extends BaseGenCfgTbl<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setTbl(String tbl) {
		set("tbl", tbl);
	}
	
	public String getTbl() {
		return getStr("tbl");
	}

	public void setGsId(Integer gsId) {
		set("gsId", gsId);
	}
	
	public Integer getGsId() {
		return getInt("gsId");
	}

}
