package com.sc.ap.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.sc.ap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRole<M extends BaseUserRole<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}
	public void setUId(Long uId) {
		set("uId", uId);
	}
	
	public Long getUId() {
		return getLong("uId");
	}

	public void setRId(Integer rId) {
		set("rId", rId);
	}
	
	public Integer getRId() {
		return getInt("rId");
	}

}
