package com.sc.ap.query;
import cn.hutool.core.util.StrUtil;
import com.sc.ap.kits.DateKit;
import com.sc.ap.core.CoreQuery;
/**
 * Generated by ap-jf.
 */
@SuppressWarnings("serial")
public class UserQuery extends CoreQuery {

	private java.lang.String loginname;
	public void setLoginname(java.lang.String loginname){
		this.loginname=loginname;
	}
	public java.lang.String getLoginname(){
		return this.loginname;
	}
	private java.lang.String nickname;
	public void setNickname(java.lang.String nickname){
		this.nickname=nickname;
	}
	public java.lang.String getNickname(){
		return this.nickname;
	}
	private java.lang.String phone;
	public void setPhone(java.lang.String phone){
		this.phone=phone;
	}
	public java.lang.String getPhone(){
		return this.phone;
	}
	private java.lang.String email;
	public void setEmail(java.lang.String email){
		this.email=email;
	}
	public java.lang.String getEmail(){
		return this.email;
	}
	private java.lang.String status;
	public void setStatus(java.lang.String status){
		this.status=status;
	}
	public java.lang.String getStatus(){
		return this.status;
	}
	//cAt比较的开始时间
	private String beginCAt;
	//cAt比较的结束时间
	private String endCAt;
	public String getBeginCAt(){
		return StrUtil.isNotBlank(this.beginCAt)?DateKit.getDateTimeBegin(this.beginCAt):null;
	}
	public void setBeginCAt(String begin){
		this.beginCAt=begin;
	}

	public String getEndCAt(){
		return StrUtil.isNotBlank(this.endCAt)?DateKit.getDateTimeEnd(this.endCAt):null;
	}
	public void setEndCAt(String end){
		this.endCAt=end;
	}


}